name: blue-recorder # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple screen recorder for Linux desktop. Supports Wayland & Xorg # 79 char long summary
description: |
  A simple desktop recorder for Linux systems. Built using Python, GTK+ 3 and ffmpeg. It supports recording audio and video on almost all Linux interfaces. Also, Blue Recorder is the first desktop program to support Wayland display server on GNOME session.
  The following formats are currently supported: mkv, avi, mp4, wmv, gif and nut (And only WebM for Wayland's GNOME session). You can stop the recording process easily by right-clicking the icon and choosing "Stop Record". Or middle-clicking the recording icon in the notifications area (but doesn't work on all interfaces).
  You can choose the audio input source you want from the list. You can also set the default values you want by simply changing them in the interface, and the program will save them for you for the next time you open it.
  Based on GREEN RECORDER but rewritten in RUST

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo

parts:
  blue-recorder:
    plugin: rust
    source: .
    stage-snaps:
      - ffmpeg
    stage-packages:
      - libgirepository1.0-dev
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - pulseaudio
      - gir1.2-appindicator3-0.1
      - libappindicator3-dev
      - libglu1-mesa
      - freeglut3
      - libgpm2
      - libslang2
      - imagemagick
      - gawk
      - gettext
      - x11-utils
      - xdg-utils
    build-packages:
      - clang
      - libappindicator3-dev
      - build-essential
    override-build: |
      snapcraftctl build
      cp -a data interfaces po $SNAPCRAFT_PART_INSTALL
      cp -a target/release/blue-recorder $SNAPCRAFT_PART_INSTALL/blue-recorder

apps:
  blue-recorder:
    command: blue-recorder
    desktop: data/blue-recorder.desktop
    extensions:
      - gnome-3-28
    plugs:
      - desktop
      - home
      - audio-playback
      - audio-record
    slots:
      - dbus-daemon
      - gnome-shell-screencast
    common-id: sa.sy.blue-recorder

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: sa.sy.blue-recorder
  gnome-shell-screencast:
    bus: session
    interface: dbus
    name: org.gnome.shell.screencast